---
id: AWCFSA
name: South America
areaConfigurations:
- areaCode: "ar"
  csvConfiguration:
    electoralListIds:
    - "AR202101"
    - "AR202301"
    - "AR202302"
    - "AR200501"
    - "AR189101"
    - "AR201101"
    - "AR189101+AR200501"
  elections:
    national:
      dates:
        66: "2001-10-14"
        67: "2003-04-27"
        68: "2005-10-23"
        69: "2007-10-28"
        70: "2009-06-28"
        71: "2011-10-23"
        72: "2013-10-27"
        73: "2015-10-25"
        74: "2017-10-22"
        75: "2019-10-27"
        76: "2021-11-14"
        77: "2023-10-22"
        78: "2025-10-26"
        79: "≤2027-10-24"
    presidential:
      dates:
        29: "2003-04-27"
        30: "2007-10-28"
        31: "2011-10-23"
        32: "2015-10-25+2015-11-22"
        33: "2019-10-27"
        34: "2023-10-22+2023-11-19"
        35: "⪅2027-10"
  translations:
    de: "Argentinien"
    en: "Argentina"
    eo: "Argentino"
    fr: "Argentine"
    nl: "Argentinië"
    no: "Argentina"
- areaCode: "bo"
  elections:
    national:
      dates:
        49: "2002-06-30"
        50: "2005-12-18"
        51: "2006-07-02"
        52: "2009-12-06"
        53: "2014-10-12"
        54: "2019-10-20"
        55: "2020-10-18"
        56: "2025-08-17"
        57: "≤2030-08"
    presidential:
      dates:
        37: "2002-06-30"
        38: "2005-12-18"
        39: "2009-12-06"
        40: "2014-10-12"
        41: "2019-10-20"
        42: "2020-10-18"
        43: "2025-08-17+2025-10-19"
        44: "≈2030-08"
  translations:
    de: "Bolivien"
    en: "Bolivia"
    eo: "Bolivio"
    fr: "Bolivie"
    nl: "Bolivia"
    no: "Bolivia"
- areaCode: "cl"
  elections:
    national:
      dates:
        59: "2001-12-16"
        60: "2005-12-11"
        61: "2009-12-13"
        62: "2013-11-17"
        63: "2017-11-19"
        64: "2021-11-21"
        65: "2025-11-16"
        66: "≤2029-11"
    presidential:
      dates:
        38: "2005-12-11+2006-01-15"
        39: "2009-12-13+2010-01-17"
        40: "2013-11-17+2013-12-15"
        41: "2017-11-19+2017-12-17"
        42: "2021-11-21+2021-12-19"
        43: "2025-11-16+2025-12-14"
        44: "≈2029-11"
  translations:
    de: "Chile"
    en: "Chile"
    eo: "Ĉilio"
    fr: "Chili"
    nl: "Chili"
    no: "Chile"
- areaCode: "co"
  csvConfiguration:
    electoralListIds:
    - "CO201301"
    - "CO184801"
    - "CO200501"
    - "CO184901"
    - "CO200502"
    - "CO200503"
    - "CO199801"
    - "CO200001"
    - "CO200901"
    - "CO201701"
  elections:
    national:
      dates:
        36: "2002-03-10"
        37: "2006-03-12"
        38: "2010-03-14"
        39: "2014-03-09"
        40: "2018-03-11"
        41: "2022-03-13"
        42: "2026-03-08"
    presidential:
      dates:
        50: "2002-05-26"
        51: "2006-05-28"
        52: "2010-05-30+2010-06-20"
        53: "2014-05-25+2014-06-15"
        54: "2018-05-27+2018-06-17"
        55: "2022-05-29+2022-06-19"
        56: "2026-05-31"
  translations:
    de: "Kolumbien"
    en: "Colombia"
    eo: "Kolombio"
    fr: "Colombie"
    nl: "Colombia"
    no: "Colombia"
- areaCode: "ec"
  elections:
    national:
      dates:
        44: "2002-10-20"
        45: "2006-10-15"
        46: "2007-09-30"
        47: "2009-04-26"
        48: "2013-02-17"
        49: "2017-02-19"
        50: "2021-02-07"
        51: "2023-08-20"
        52: "2025-02-09"
        53: "≤2029-02"
    presidential:
      dates:
        30: "2002-10-20"
        31: "2006-10-15"
        32: "2009-04-26"
        33: "2013-02-17"
        34: "2017-02-19+2017-04-02"
        35: "2021-02-07+2021-04-11"
        36: "2023-08-20+2023-10-15"
        37: "2025-02-09+2025-04-13"
        38: "≈2029-02"
  translations:
    de: "Ecuador"
    en: "Ecuador"
    eo: "Ekvadoro"
    fr: "Équateur"
    nl: "Ecuador"
    no: "Ecuador"
- areaCode: "fk"
  elections:
    national:
      dates:
        15: "2001-11-22"
        16: "2005-11-17"
        17: "2009-11-05"
        18: "2013-11-07"
        19: "2017-11-09"
        20: "2021-11-04"
        21: "2025-12-11"
        22: "≤2029-12"
  translations:
    de: "Falklandinseln"
    en: "Falkland Islands"
    eo: "Insuloj Falklandoj"
    fr: "Îles Malouines"
    nl: "Falklandeilanden"
    no: "Falklandsøyene"
- areaCode: "gy"
  elections:
    national:
      dates:
        22: "2001-03-19"
        23: "2006-08-28"
        24: "2011-11-28"
        25: "2015-05-11"
        26: "2020-03-02"
        27: "2025-09-01"
        28: "≤2030-09"
  translations:
    de: "Guyana"
    en: "Guyana"
    eo: "Gujano"
    fr: "Guyana"
    nl: "Guyana"
    no: "Guyana"
- areaCode: "pe"
  csvConfiguration:
    electoralListIds:
    - "PE193001"
    - "PE200001"
    - "PE199701"
    - "PE200501"
    - "PE195601"
    - "PE199702"
    - "PE199401"
    - "PE199801"
    - "PE199402"
    - "PE198901+PE199201+PE199701"
    - "PE198901+PE199701"
    - "PE200502"
    - "PE200601"
    - "PE201001"
    - "PE201401"
    - "PE201501"
    - "PE201502"
    - "PE200201"
    - "PE201002"
    - "PE201301"
    - "PE200101"
    - "PE200102"
    - "PE201601"
    - "PE196601"
    - "PE198902"
    - "PE201701"
    - "PE200801"
    - "PE201801"
    - "PE202001"
    - "PE201702"
    - "PE202002"
    - "PE202101"
    - "PE202102"
    - "PE202301"
    - "PE202103"
    - "PE201703"
    - "PE202302"
  elections:
    national:
      dates:
        40: "2000-04-09"
        41: "2001-04-08"
        42: "2006-04-09"
        43: "2011-04-10"
        44: "2016-04-10"
        45: "2020-01-26"
        46: "2021-04-11"
        47: "2026-04-12"
    presidential:
      dates:
        37: "2000-04-09+2000-05-28"
        38: "2001-04-08+2001-06-03"
        39: "2006-04-09+2006-06-04"
        40: "2011-04-10+2011-06-05"
        41: "2016-04-10+2016-06-05"
        42: "2021-04-11+2021-06-06"
        43: "2026-04-12"
  translations:
    de: "Peru"
    en: "Peru"
    eo: "Peruo"
    fr: "Pérou"
    nl: "Peru"
    no: "Peru"
- areaCode: "sr"
  elections:
    national:
      dates:
        53: "2000-05-25"
        54: "2005-05-25"
        55: "2010-05-25"
        56: "2015-05-25"
        57: "2020-05-25"
        58: "2025-05-25"
        59: "≤2030-05"
  translations:
    de: "Suriname"
    en: "Suriname"
    eo: "Surinamo"
    fr: "Suriname"
    nl: "Suriname"
    no: "Surinam"
- areaCode: "ve"
  elections:
    national:
      dates:
        34: "2000-07-30"
        35: "2005-12-04"
        36: "2010-10-26"
        37: "2015-12-06"
        38: "2020-12-06"
        39: "2025-05-25"
        40: "≤2030-05"
    presidential:
      dates:
        11: "2000-07-30"
        12: "2006-12-03"
        13: "2012-10-07"
        14: "2013-04-14"
        15: "2018-05-20"
        16: "2024-07-28"
        17: "≈2030-07"
  translations:
    de: "Venezuela"
    en: "Venezuela"
    eo: "Venezuelo"
    fr: "Venezuela"
    nl: "Venezuela"
    no: "Venezuela"
widgetsConfiguration:
  tableFontFamily: "Alegreya Sans,'Helvetica Neue',Helvetica,sans-serif"
  tableStylesheets:
  - https://fonts.googleapis.com/css?family=Alegreya+Sans%3A400%2C700%2C400italic%2C700italic%2C600%2C600italic%7CAlegreya+Sans%3A400%2C500%2C600%2C700%2C400italic%2C700italic&ver=1
  - https://europeelects.eu/wp-content/themes/chaplin/style.css?ver=2.6.7
